export const UPDATE_SOCKET_VAR = 'UPDATE_SOCKET_VAR'

export const UPDATE_TRACK_NAME = 'UPDATE_TRACK_NAME'

export const UPDATE_PLAYLIST_NAME = 'UPDATE_PLAYLIST_NAME'

export const UPDATE_PLAYER_POSITION = 'UPDATE_PLAYER_POSITION'

export const UPDATE_VOLUME = 'UPDATE_VOLUME'

export const UPDATE_TRACKS_DATA = 'UPDATE_TRACKS_DATA'

export const UPDATE_PLAYER_STATE = 'UPDATE_PLAYER_STATE'

export const UPDATE_PLAYLISTS = 'UPDATE_PLAYLISTS'
